<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="ViewRewards.aspx.cs" Inherits="ViewRewards" %>


<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

<asp:Panel ID ="masterPanel" runat ="server">
<div style ="position: relative; top: 60px;">

    <%-- Sidebar --%>
    <div style = "float: left; width: 15%;">
                    <ul id="slide-out" class="side-nav fixed" style = "width:15%;">
                            <li><div class="user-view">
                                <asp:Image ID ="profilePicture" Height ="120px" Width ="120px" CssClass ="circle user" runat ="server"/>
                                <asp:Label ID="lblUser" runat="server" Text="" CssClass ="user1"></asp:Label>
                                <asp:Label ID="lblBalance" runat="server" CssClass ="user1"></asp:Label>
                            </div></li>
                            <li><a href ="/UserOptions.aspx">User Options</a></li>
                            <li><a href="/ViewRewards.aspx">View Rewards</a></li>
                            <li><a href ="/AddRewardProviders.aspx">View Reward Providers</a></li>
                            <li><a href="/CompanyValues.aspx">View Company Values</a></li>
                            <li><a href="PendingApplications.aspx">Pending Applications</a></li>
                            <li><a href="AnalyticsPage.aspx">View Analytics</a></li>
                            <li><a href="/adminCalendar.aspx">Community Events</a></li>
                            <li><a href="/Default.aspx">Logout</a></li>
                    </ul>
                </div>

    <%-- Content --%>
    <div style ="float: right; width: 85%;">
        <div style = "margin-left:auto; margin-right:auto; width:85%;">
        <nav class="feednav" >
            <div class="nav-wrapper">
                <a class="brand-logo nav1 panel">Rewards</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down"> 
                    
    
                    <asp:Label ID = "lblResult" runat ="server"/>
                    <%-- Options Here --%>
                </ul>
            </div>


        </nav>
        <div style ="background-color: white;">
            <asp:GridView ID="pendingRewardsGrid" runat="server" DataKeyNames="ProviderName" AutoGenerateColumns="false" AutoGenerateEditButton="true" OnRowEditing="pendingRewardsGrid_RowEditing" AutoGenerateDeleteButton="true" OnRowDeleting="pendingRewardsGrid_RowDeleting" OnRowUpdating="pendingRewardsGrid_RowUpdating" OnRowCancelingEdit="pendingRewardsGrid_RowCancelingEdit">

                <Columns>
                    <asp:TemplateField HeaderText="Provider Name">
                        <ItemTemplate>
                            <asp:Label ID="lblProviderName" runat="server" Text='<%# Eval("ProviderName") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Reward Name">
                        <ItemTemplate>
                            <asp:Label ID="lblRewardName" runat="server" Text='<%# Eval("RewardName") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Reward Quantity">
                        <ItemTemplate>
                            <asp:Label ID="lblRewardQuantity" runat="server" Text='<%# Eval("RewardQuantity") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Reward Amount">
                        <ItemTemplate>
                            <asp:Label ID="lblRewardAmount" runat="server" Text='<%# Eval("RewardAmount") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Pending Approval">
                        <EditItemTemplate>
                            <asp:DropDownList ID="drpApproval" runat="server" SelectedValue='<%# Bind("PendingReview") %>'>
                                <asp:ListItem Value="0">Approved</asp:ListItem>
                                <asp:ListItem Value="1">Not Approved</asp:ListItem>
                            </asp:DropDownList>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblApproval" runat="server" Text='<%# Eval("PendingReview") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Date Added">
                        <ItemTemplate>
                            <asp:Label ID="lblDateAdded" runat="server" Text='<%# Eval("DateAdded") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

            </asp:GridView>

        </div>
            <asp:Panel ID ="Panel1" runat="server"></asp:Panel>
       
        </div>
    </div>
</div>

<asp:Panel ID ="Popup" runat ="server" BackColor ="white" CssClass ="popupPanel" Visible ="false" Enabled ="false">
    <table>
        <tr>
            <td>
                <asp:Label ID ="lblMsg" runat ="server" CssClass ="popupLabels"></asp:Label>
            </td>
        </tr>
        <tr>
            <td>
                <asp:Button ID ="btnDelete" Text ="Delete" OnClick ="delete_Click" CssClass ="btn" runat ="server" ForeColor ="Red"/>
            </td>
            <td>
                <asp:Button ID ="btnCancel" Text = "Cancel" OnClick ="cancel_Click" CssClass ="btn" runat ="server" />
            </td>
        </tr>
    </table>
    
</asp:Panel>
</asp:Panel>
    



    
</asp:Content>
